### PR TITLE
Randomized dates, terms, and locations.

### PR DESCRIPTION
**Pull request by justinpearson**
This PR addresses issue #90 .

### CODE REVIEW

**Comment by carsonkk** [comment]
screenshot from 2017-11-20 13-01-12

**Comment by justinpearson** [comment]
Yes, those are placeholders for terms that folks might place. How about if
I make them a bulleted list?

**Comment by carsonkk** [comment]
Did not see your comment before I committed that, I just added a join call so that you dont see the brackets ie it doesnt look like an array

**Comment by carsonkk** [comment]
screenshot from 2017-11-20 13-15-51

**Comment by justinpearson** [comment]
Thx Kyle.

**Pull request merged**
