### PR TITLE
Added a Rent button for each car that partially fills out a new RP

### PR DESCRIPTION
**Pull request by justinpearson**
This PR addresses issue #49 .  (Users can rent cars)

Description (if needed):
- put a "Rent Me" button next to each car that redirects user to a new Rental Post page.

### CODE REVIEW

**Comment by carsonkk** [comment]
What do we want to do with this?

**Comment by masoug** [comment]
pinging justin @justinpearson

**Comment by justinpearson** [comment]
@masoug , The idea was to have a "Rent" button that lets a user rent a car. In the old days this amounted to filling in the renter's user_id into the rental post. However, Kyle moved past that with his idea of a RP having a "state": open, rented, in-progress, cancelled, etc. So I think we can close this one. Although let me check if there's anything worth keeping from the rent-car-flow branch.

**Comment by justinpearson** [comment]
There are a couple changes we might want to keep from this branch:

- separate out the "filled" RPs from the "available" RPs
- db seed file creates both filled and available RPs
- shows user's RPs: what they've rented, and what they're offering

How about if I break these into separate PRs.

**Comment by justinpearson** [comment]
Equivalent functionality has been achieved through other PRs.

**Pull request closed without merging**
