### PR TITLE
Setup framework for allowing only authorized users to modify their own profile and view rental posts

### PR DESCRIPTION
**Pull request by masoug**
> extended session features to prevent users from viewing each other's stuff. see related issues #60 and #59.
> 
> users can not view each others profile. guests can not create, update, and destroy rental posts. I also added some tests to verify some of this behavior. however there are some issues with the template rendering (i.e. rails barfs when I try to list the index of rental posts).

there are a lot of tests that have to be added to check these authentication guards. this is a start, but we will need to check that users can not mess with other people's cars and rental posts.

### CODE REVIEW

**Comment by masoug** [comment]
follow-up: only users of their own rental posts can edit/destroy.

**Comment by carsonkk** [comment]
@masoug my PR is going to break a lot of your tests since there's major changes to the models/data schema, might want to rebase on it first

**Comment by carsonkk** [comment]
@masoug So I just tested this and a lot of URL's still aren't getting redirected, but I'm not sure exactly which ones this PR is addressing. I've made a list of everything I could think of below, but if you want to address them in a separate ticket feel free to merge this one.

- Things that seem to be working:

As a guest user, I get redirected to the login page when I try...
/rentals/:id/edit
/users/:id/edit

As a logged in user, I get redirected to the home page when I try...
/users/:id/edit (but there should be a flash message added telling me why i've been redirected)

- The following are still an issue:

As a guest user, I can (incorrectly) see:
/rentals
/rentals/:id
/cars/:id
/cars/:id/edit
/users/:id/[overview, rentals, cars, history, settings]

As a logged in user I can (incorrectly) see:
/rentals/:id (for posts that have both a renter and an owner, neither of which are me. I should only be able to see rental posts that have no renter or rental posts where I am one of the two parties)
/rentals/:id/edit (I should only be able to see this as the owner but I can see any of them)
/cars/:id (for cars I don't own)
/cars/:id/edit (for cars I don't own)
/users/:id/[rentals, cars, history, settings] (of other users)

**Comment by masoug** [comment]
yea so the changes in this particular PR are just the ones you mentioned already:

> As a guest user, I get redirected to the login page when I try...
> /rentals/:id/edit
> /users/:id/edit

adding redirects to the other ones will probably be another PR since we'll need to add corresponding tests for them. thats a lot of changes in one step so i think its best to split them up into multiple PRs so we minimize the probability of merge conflicts.

**Comment by carsonkk** [comment]
I agree, just wanted to make sure we were on the same page and post my findings

**Comment by justinpearson** [comment]
Nice sleuthing you two. Are there new PRs for these new items or should I make them?

**Comment by masoug** [comment]
@justinpearson feel free to create them and assign to me

**Pull request merged**
