### PR TITLE
Fix test case issue

### PR DESCRIPTION
**Pull request by Heronalps**
This PR addresses issue - Basic data model for a user #11 . 

Description (if needed):

Create user model based on our discussion and fix the test case issue.

### CODE REVIEW

**Comment by masoug** [comment]
This looks like it changes the car model. Are these changes for the user model?

**Comment by Heronalps** [comment]
The car model is consistent and it should belong to one user. User should have many cars and rental posts. Any question about that?

**Comment by masoug** [comment]
Okay I was just a little confused that the `user_model` branch contains changes to the car model.

**Comment by justinpearson** [comment]
I think the user_model branch contained models for User, Car, and RentalPost.

**Comment by justinpearson** [comment]
@Heronalps as the owner of this branch you can merge this into master.

**Pull request merged**
